const $ = id => document.getElementById(id);
const bootConsole=$('bootConsole'), term=$('term'), cmdInput=$('cmd'), runBtn=$('runBtn'), aiPrompt=$('aiPrompt'), aiOut=$('aiOut'), askAiBtn=$('askAiBtn'), streamAiBtn=$('streamAiBtn'), policyBtn=$('policyBtn'), healthChip=$('healthChip'), bootChip=$('bootChip'), authChip=$('authChip'), clockChip=$('clockChip'), userInput=$('userInput'), passInput=$('passInput'), loginBtn=$('loginBtn'), jobsBtn=$('jobsBtn'), docsBtn=$('docsBtn'), sessionOut=$('sessionOut'), pathInput=$('pathInput'), editorArea=$('editorArea'), loadFileBtn=$('loadFileBtn'), saveFileBtn=$('saveFileBtn'), snapshotBtn=$('snapshotBtn'), restoreInput=$('restoreInput'), restoreBtn=$('restoreBtn'), bootStatusBtn=$('bootStatusBtn'), quickstartBtn=$('quickstartBtn'), recoveryBtn=$('recoveryBtn');
let token = localStorage.getItem('one2lv_token') || ''; const history=[]; let historyIndex=-1;
const setAuthState=()=>authChip.textContent=token?'admin':'guest'; setAuthState();
setInterval(()=>clockChip.textContent=new Date().toLocaleString(),1000); clockChip.textContent=new Date().toLocaleString();
function writeToBox(box,text=''){ const el=document.createElement('div'); el.textContent=typeof text==='string'?text:JSON.stringify(text,null,2); box.appendChild(el); box.scrollTop=box.scrollHeight; }
function pretty(obj){ return typeof obj==='string'?obj:JSON.stringify(obj,null,2); }
function banner(){ writeToBox(term,'one2lvos_v4 ready'); writeToBox(term,'Commands: help | login | policy | task list | task run boot.status | task run docs.read operator_quickstart.md'); writeToBox(term,''); } banner();
async function getJson(url, options={}){ const headers={...(options.headers||{})}; if(token) headers.Authorization=`Bearer ${token}`; const res=await fetch(url,{...options,headers}); const data=await res.json(); if(!res.ok||data.ok===false) throw new Error(data.error||`Request failed: ${res.status}`); return data; }
async function checkHealth(){ try{ const data=await getJson('/api/health'); healthChip.textContent=`${data.app} online`; } catch { healthChip.textContent='offline'; } } checkHealth();
async function login(){ const data=await getJson('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:userInput.value,password:passInput.value})}); token=data.token; localStorage.setItem('one2lv_token',token); setAuthState(); sessionOut.textContent='login ok'; }
async function queueTask(task,payload={}){ return getJson('/api/tasks/run',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({task,payload})}); }
async function loadBootState(){ bootConsole.innerHTML=''; try{ const data=await getJson('/api/boot/state'); const {state,checklist}=data; bootChip.textContent=state.recoveryMode?'recovery mode':'normal boot'; writeToBox(bootConsole,'ONE2LV ATOMIC RECOVERY BOOT'); writeToBox(bootConsole,`boot count: ${state.bootCount}`); writeToBox(bootConsole,`last boot: ${state.lastBootAt}`); writeToBox(bootConsole,`previous shutdown clean: ${state.cleanShutdown?'yes':'no'}`); writeToBox(bootConsole,state.recoveryMode?'Status: recovery guidance recommended.':'Status: normal boot.'); writeToBox(bootConsole,''); writeToBox(bootConsole,'Safe next steps:'); for(const step of checklist.steps) writeToBox(bootConsole,`${step.id}. ${step.label}`); } catch(error){ bootChip.textContent='boot error'; writeToBox(bootConsole,error.message); } } loadBootState();
async function runTerminalCommand(raw){ const text=raw.trim(); if(!text) return; writeToBox(term,`~ # ${text}`); if(text==='help'){ ['help','login','policy','task list','task run boot.status','task run docs.list','task run docs.read operator_quickstart.md','task run boot.snapshot','drive list','moltbook me','search <query>','ai <prompt>'].forEach(x=>writeToBox(term,x)); return; } if(text==='login'){ await login(); writeToBox(term,'login ok'); return; } if(text==='policy'){ const data=await getJson('/api/system/policy'); writeToBox(term,pretty(data.policy)); return; } if(text==='task list'){ const data=await getJson('/api/tasks'); writeToBox(term,pretty(data.tasks)); return; } if(text.startsWith('search ')){ const q=text.slice(7); const data=await getJson(`/api/search?q=${encodeURIComponent(q)}`); writeToBox(term,pretty(data.results)); return; } if(text==='drive list'){ const data=await getJson('/api/drive/list'); writeToBox(term,pretty(data.files)); return; } if(text==='moltbook me'){ const data=await getJson('/api/moltbook/me'); writeToBox(term,pretty(data.profile)); return; } if(text.startsWith('task run ')){ const rest=text.replace(/^task run\s+/,'').trim(); const parts=rest.split(/\s+/); const task=parts.shift(); let payload={}; if(['package.install','package.update','service.restart'].includes(task)) payload={name:parts[0]||''}; else if(task==='docs.read') payload={name:parts[0]||'operator_quickstart.md'}; else if(task==='boot.restore') payload={snapshotId:parts[0]||'', targetPath:'notes.txt'}; const data=await queueTask(task,payload); writeToBox(term,pretty(data.result||data.job)); return; } if(text.startsWith('ai ')){ const prompt=text.slice(3); const data=await getJson('/api/ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt})}); writeToBox(term,pretty(data.output)); return; } writeToBox(term,'command not found'); }
runBtn.addEventListener('click', async ()=>{ try{ const raw=cmdInput.value; if(!raw.trim()) return; history.push(raw); historyIndex=history.length; cmdInput.value=''; await runTerminalCommand(raw); } catch(error){ writeToBox(term,`error: ${error.message}`); } });
cmdInput.addEventListener('keydown', event=>{ if(event.key==='Enter') runBtn.click(); else if(event.key==='ArrowUp'){ if(historyIndex>0){ historyIndex-=1; cmdInput.value=history[historyIndex]; event.preventDefault(); } } else if(event.key==='ArrowDown'){ if(historyIndex<history.length-1){ historyIndex+=1; cmdInput.value=history[historyIndex]; } else { historyIndex=history.length; cmdInput.value=''; } event.preventDefault(); } });
askAiBtn.addEventListener('click', async ()=>{ const prompt=aiPrompt.value.trim(); if(!prompt) return; aiOut.textContent='working…'; try{ const data=await getJson('/api/ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt})}); aiOut.textContent=pretty(data.output); } catch(error){ aiOut.textContent=error.message; } });
streamAiBtn.addEventListener('click', ()=>{ const prompt=aiPrompt.value.trim(); if(!prompt) return; aiOut.textContent=''; const source=new EventSource(`/api/ai/stream?prompt=${encodeURIComponent(prompt)}`); source.addEventListener('message', event=>aiOut.textContent += `${event.data}
`); source.addEventListener('done', ()=>source.close()); source.addEventListener('error', ()=>{ aiOut.textContent += '
[stream ended]
'; source.close(); }); });
policyBtn.addEventListener('click', async ()=>{ try{ const data=await getJson('/api/system/policy'); aiOut.textContent=pretty(data.policy); } catch(error){ aiOut.textContent=error.message; } });
loginBtn.addEventListener('click', async ()=>{ try{ await login(); } catch(error){ sessionOut.textContent=error.message; } });
jobsBtn.addEventListener('click', async ()=>{ try{ const data=await getJson('/api/jobs'); sessionOut.textContent=pretty(data.jobs); } catch(error){ sessionOut.textContent=error.message; } });
docsBtn.addEventListener('click', async ()=>{ try{ const data=await getJson('/api/docs'); sessionOut.textContent=pretty(data.docs); } catch(error){ sessionOut.textContent=error.message; } });
loadFileBtn.addEventListener('click', async ()=>{ try{ const path=encodeURIComponent(pathInput.value||'notes.txt'); const data=await getJson(`/api/editor/read?path=${path}`); editorArea.value=data.content; sessionOut.textContent=`loaded ${data.path}`; } catch(error){ sessionOut.textContent=error.message; } });
saveFileBtn.addEventListener('click', async ()=>{ try{ const data=await getJson('/api/editor/write',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({path:pathInput.value,content:editorArea.value})}); sessionOut.textContent=pretty(data.result); } catch(error){ sessionOut.textContent=error.message; } });
snapshotBtn.addEventListener('click', async ()=>{ try{ const data=await getJson('/api/boot/snapshot',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({path:pathInput.value,label:'manual'})}); sessionOut.textContent=pretty(data.snapshot); restoreInput.value=data.snapshot.id; await loadBootState(); } catch(error){ sessionOut.textContent=error.message; } });
restoreBtn.addEventListener('click', async ()=>{ try{ const data=await getJson('/api/boot/restore',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({snapshotId:restoreInput.value,targetPath:pathInput.value})}); sessionOut.textContent=pretty(data.result); } catch(error){ sessionOut.textContent=error.message; } });
bootStatusBtn.addEventListener('click', loadBootState);
quickstartBtn.addEventListener('click', async ()=>{ try{ const data=await getJson('/api/docs/read?name=operator_quickstart.md'); bootConsole.innerHTML=''; writeToBox(bootConsole,data.content); } catch(error){ bootConsole.innerHTML=''; writeToBox(bootConsole,error.message); } });
recoveryBtn.addEventListener('click', async ()=>{ try{ const data=await getJson('/api/docs/read?name=recovery.md'); bootConsole.innerHTML=''; writeToBox(bootConsole,data.content); } catch(error){ bootConsole.innerHTML=''; writeToBox(bootConsole,error.message); } });
document.querySelectorAll('[data-cmd]').forEach(btn=>btn.addEventListener('click', ()=>{ cmdInput.value=btn.dataset.cmd||''; runBtn.click(); }));
