import express from "express";
import cors from "cors";
import helmet from "helmet";
import morgan from "morgan";
import path from "path";
import { fileURLToPath } from "url";
import dotenv from "dotenv";
import authRouter from "./src/routes/auth.js";
import aiRouter from "./src/routes/ai.js";
import driveRouter from "./src/routes/drive.js";
import moltbookRouter from "./src/routes/moltbook.js";
import searchRouter from "./src/routes/search.js";
import systemRouter from "./src/routes/system.js";
import taskRouter from "./src/routes/tasks.js";
import jobsRouter from "./src/routes/jobs.js";
import editorRouter from "./src/routes/editor.js";
import bootRouter from "./src/routes/boot.js";
import docsRouter from "./src/routes/docs.js";
import { ensureWorkspace } from "./src/lib/fs-guard.js";
import { initBootState, markCleanShutdownOnSignals } from "./src/lib/boot-state.js";
dotenv.config();
ensureWorkspace();
await initBootState();
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const frontendDir = path.resolve(__dirname, "../frontend");
const app = express();
const PORT = Number(process.env.PORT || 8080);
const HOST = process.env.HOST || "0.0.0.0";
app.use(helmet({ contentSecurityPolicy: false }));
app.use(cors());
app.use(morgan("dev"));
app.use(express.json({ limit: "1mb" }));
app.use(express.static(frontendDir));
app.get('/api/health', (_req, res) => res.json({ ok:true, app:'one2lvos_v4', time:new Date().toISOString() }));
app.use('/api/auth', authRouter);
app.use('/api/ai', aiRouter);
app.use('/api/drive', driveRouter);
app.use('/api/moltbook', moltbookRouter);
app.use('/api/search', searchRouter);
app.use('/api/system', systemRouter);
app.use('/api/tasks', taskRouter);
app.use('/api/jobs', jobsRouter);
app.use('/api/editor', editorRouter);
app.use('/api/boot', bootRouter);
app.use('/api/docs', docsRouter);
app.get('*', (_req,res)=>res.sendFile(path.join(frontendDir,'index.html')));
const server = app.listen(PORT, HOST, () => console.log(`one2lvos_v4 listening on http://${HOST}:${PORT}`));
markCleanShutdownOnSignals(server);
