import { appendAuditLine, readJsonFile, writeJsonFile, readWorkspaceFile, writeWorkspaceFile, listWorkspace, copyFileWithinWorkspace } from './fs-guard.js';
import { searchWorkspace } from './search.js';
const BOOT_FILE='boot-state.json';
function defaultState(){ return {lastBootAt:null,lastShutdownAt:null,cleanShutdown:true,bootCount:0,recoveryMode:false,snapshots:[]}; }
export function getBootState(){ return readJsonFile(BOOT_FILE, defaultState()); }
export async function initBootState(){ const state=getBootState(); const next={...state,lastBootAt:new Date().toISOString(),bootCount:(state.bootCount||0)+1,recoveryMode:state.cleanShutdown===false,cleanShutdown:false}; writeJsonFile(BOOT_FILE,next); appendAuditLine(`[${next.lastBootAt}] BOOT recoveryMode=${next.recoveryMode}`); }
export async function markCleanShutdown(){ const state=getBootState(); const next={...state,lastShutdownAt:new Date().toISOString(),cleanShutdown:true,recoveryMode:false}; writeJsonFile(BOOT_FILE,next); appendAuditLine(`[${next.lastShutdownAt}] SHUTDOWN clean`); }
export function markCleanShutdownOnSignals(server){ const close=async()=>{ try{ await markCleanShutdown(); } finally { server.close(()=>process.exit(0)); } }; process.on('SIGINT',close); process.on('SIGTERM',close); }
export function createSnapshot(sourcePath='notes.txt', label='manual'){ const state=getBootState(); const stamp=Date.now(); const target=`.snapshots/${stamp}-${label}.txt`; copyFileWithinWorkspace(sourcePath,target); const snapshot={id:`snap_${stamp}`,label,sourcePath,targetPath:target,createdAt:new Date().toISOString()}; const next={...state,snapshots:[snapshot,...(state.snapshots||[])].slice(0,20)}; writeJsonFile(BOOT_FILE,next); appendAuditLine(`[${snapshot.createdAt}] SNAPSHOT ${snapshot.id} ${sourcePath} -> ${target}`); return snapshot; }
export function restoreSnapshot(snapshotId,targetPath='notes.txt'){ const state=getBootState(); const found=(state.snapshots||[]).find(s=>s.id===snapshotId); if(!found) throw new Error('Snapshot not found'); const text=readWorkspaceFile(found.targetPath); writeWorkspaceFile(targetPath,text); appendAuditLine(`[${new Date().toISOString()}] RESTORE ${snapshotId} -> ${targetPath}`); return {ok:true,snapshot:found,restoredTo:targetPath}; }
export function getRecoveryChecklist(){ const state=getBootState(); const notesExists=!!listWorkspace('.').find(i=>i.name==='notes.txt'); const recoveryMentions=searchWorkspace('Recovery'); return { recoveryMode:state.recoveryMode, steps:[ {id:1,label:'Read operator quickstart',endpoint:'/api/docs/read?name=operator_quickstart.md'}, {id:2,label:'Read recovery manual',endpoint:'/api/docs/read?name=recovery.md'}, {id:3,label:'Inspect system policy',endpoint:'/api/system/policy'}, {id:4,label:'Check workspace notes',endpoint:'/api/editor/read?path=notes.txt'}, {id:5,label:'Create snapshot before edits',endpoint:'/api/boot/snapshot'} ], status:{notesExists,docsIndexed:true,recoveryMentionsInWorkspace:recoveryMentions.length} }; }
